package ec.edu.ups.servicios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-06-23T22:36:07.680-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "TransaccionesSOAPService", 
                  wsdlLocation = "file:TransaccionesSOAP_1.wsdl",
                  targetNamespace = "http://servicios.ups.edu.ec/") 
public class TransaccionesSOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicios.ups.edu.ec/", "TransaccionesSOAPService");
    public final static QName TransaccionesSOAPPort = new QName("http://servicios.ups.edu.ec/", "TransaccionesSOAPPort");
    static {
        URL url = null;
        try {
            url = new URL("file:TransaccionesSOAP_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransaccionesSOAPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/TransaccionesSOAP_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransaccionesSOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransaccionesSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransaccionesSOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransaccionesSOAPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransaccionesSOAPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TransaccionesSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TransaccionesSOAP
     */
    @WebEndpoint(name = "TransaccionesSOAPPort")
    public TransaccionesSOAP getTransaccionesSOAPPort() {
        return super.getPort(TransaccionesSOAPPort, TransaccionesSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransaccionesSOAP
     */
    @WebEndpoint(name = "TransaccionesSOAPPort")
    public TransaccionesSOAP getTransaccionesSOAPPort(WebServiceFeature... features) {
        return super.getPort(TransaccionesSOAPPort, TransaccionesSOAP.class, features);
    }

}
