package ec.edu.ups.servicios;

import ec.edu.ups.common.Exception_Exception;
import ec.edu.ups.common.ObjectFactory;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2020-06-23T22:36:07.674-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://servicios.ups.edu.ec/", name = "TransaccionesSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface TransaccionesSOAP {

    @WebMethod
    @RequestWrapper(localName = "transaccionDepostio", targetNamespace = "http://servicios.ups.edu.ec/", className = "ec.edu.ups.servicios.TransaccionDepostio")
    @ResponseWrapper(localName = "transaccionDepostioResponse", targetNamespace = "http://servicios.ups.edu.ec/", className = "ec.edu.ups.servicios.TransaccionDepostioResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String transaccionDepostio(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "transaccionTransferencia", targetNamespace = "http://servicios.ups.edu.ec/", className = "ec.edu.ups.servicios.TransaccionTransferencia")
    @ResponseWrapper(localName = "transaccionTransferenciaResponse", targetNamespace = "http://servicios.ups.edu.ec/", className = "ec.edu.ups.servicios.TransaccionTransferenciaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String transaccionTransferencia(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2
    );

    @WebMethod
    @RequestWrapper(localName = "transaccionRetiro", targetNamespace = "http://servicios.ups.edu.ec/", className = "ec.edu.ups.servicios.TransaccionRetiro")
    @ResponseWrapper(localName = "transaccionRetiroResponse", targetNamespace = "http://servicios.ups.edu.ec/", className = "ec.edu.ups.servicios.TransaccionRetiroResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String transaccionRetiro(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1
    ) throws Exception_Exception;
}
